config/routes.rb
Blog::Application.routes.draw do
  resources :users
  resources :posts
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to: "static_pages#index"

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/help'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/sign_up', to: 'users#new', via: 'get'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	default_scope -> { order('created_at DESC') }
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
	validates :body, presence: true
	validates :title, presence: true

	has_attached_file :picture, styles: { medium: "600x400>", thumb: "400x200>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

	before_create :create_remember_token

	validates :name, presence: true, length: { maximum: 30 }, uniqueness: true

	has_secure_password

	validates :password_digest, length: { minimum: 6 }

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end
  	private

  	def create_remember_token
      	self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def new
		@comment = Comment.new
	end

	def create
		@comment = current_user.comments.create(comment_params)
		@post = Post.find(comment_params[:post_id])
		@user = current_user
		@comments_count = @post.comments.count
		respond_to do |format|
			format.html { redirect_to @post }
			format.js 	{ }
		end
	end

	def destroy
		@comment = current_user.comments.find_by_id(params[:id])
		@comments_count = Post.find(@comment.post_id).comments.count
		@post = Post.find(@comment.post_id)
		@comment.destroy
		respond_to do |format|
      		format.html { redirect_to @post }
      		format.json { head :no_content }
      		format.js   { render :layout => false }
    	end
	end

	private
	def comment_params
		params.require(:comment).permit(:content, :post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :signed_in_user

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created"
			redirect_to current_user
		else
			redirect_to root_url
		end
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
		@user = User.find(@post.user_id)
		@comment = Comment.new
		@comments = @post.comments.paginate(page: params[:page], per_page: 10)
	end

	def destroy
	end
	
	def post_params
		params.require(:post).permit(:title, :body, :picture)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render 'new'
	end

	def create
		user = User.find_by_name(params[:session][:name])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = "Invalid name/email"
			render 'new'
		end
	end

	def destroy
		sign_out
    	redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		@posts = Post.paginate(page: params[:page], per_page: 20)
	end

	def about
	end

	def contact
	end

	def help
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, 	only: [:edit, :update, :index, :destroy]
	before_action :correct_user, 	only: [:edit, :update]
	before_action :admin_user, only: [:destroy]
	
	def index
		 @users = User.paginate(page: params[:page], per_page: 20)
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page], per_page: 20)
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the DAA BLOG!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated succesfully"
			redirect_to @user
		else
			flash.now[:success] = "Name/password invalid"
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User deleted."
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :password, :password_confirmation, :avatar)
	end

	def correct_user
		@user = User.find(params[:id])
		if !current_user?(@user)
			flash[:error] = "Access is block"
			redirect_to root_url
		end
	end

	def admin_user
		if !current_user.admin?
			redirect_to root_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def abbreviated_post(post)
		text = post.body
		result = text

		if text.length > 300
			result = text[0..300]
			result << '...'
		end

		result
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
	    remember_token = User.new_remember_token
	    cookies.permanent[:remember_token] = remember_token #permanent -- 20.years.from_now :)
	    user.update_attribute(:remember_token, User.encrypt(remember_token))
	    self.current_user = user
	end

	def sign_out
    	current_user.update_attribute(:remember_token,
                                User.encrypt(User.new_remember_token))
    	cookies.delete(:remember_token)
    	self.current_user = nil
  	end

	def signed_in?
    	!current_user.nil?
  	end

  	def signed_in_user
		redirect_to signin_url, notice: "Please, sign in." unless signed_in? 
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
	    remember_token = User.encrypt(cookies[:remember_token])
	    @current_user ||= User.find_by(remember_token: remember_token)
  	end

  	def current_user?(user)
  		user == current_user
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def medium_avatar_for(user)
		image_tag user.avatar.url(:medium)
	end

	def thumb_avatar_for(user)
		image_tag user.avatar.url(:thumb), :class => "img-circle"
	end
end

app/views/comments/_comment.html.erb
<div class="container-fluid comment">
  <div class="row">

	<% user = User.find(comment.user_id) %>
    <div class="col-md-4">
      <%= thumb_avatar_for user %>
      <h3><%= link_to user.name, user %></h3>
      <h6>Email: email@mail.ru</h6>
      <h6>Old: 20 Year</h6>
      <h6><%= link_to "All posts...", user %></h6>
    </div>
    
    <div class="col-sm-8" style="background-color:none;">
    	<%= comment.content %>
    </div>   
  </div>
 
 	<span class="text-muted">
	    Commented <%= time_ago_in_words(comment.created_at) %> ago.
	</span>
   <% if current_user? user %>
    | <%= link_to "delete", comment, method: :delete, remote: true, :class => "del-button"%>
  <% end %>
  	<hr>
</div>

 

app/views/comments/_form.html.erb
<%= form_for @comment, :remote => true do |f| %>
	<div class = "field">
		<%= f.text_area :content %>
	</div>
	<div class = "field">
		<%= f.hidden_field :post_id, :value => @post.id %>
	</div>
	<div class = "actions">
		<%= f.submit "Add comment", class: "btn btn-primary"%>
	</div>
<% end %>

app/views/comments/create.js.erb
$(document).ready(function() {
	$("div.comments-render").append('<div class="container-fluid comment">\
	  	<div class="row">\
			<div class="col-md-4">\
	      		<%= thumb_avatar_for @user %>\
	      		<h3><%= link_to @user.name, @user %></h3>\
	      		<h6>Email: email@mail.ru</h6>\
	      		<h6>Old: 20 Year</h6>\
	      		<h6><%= link_to "All posts...", @user %></h6>\
	    	</div>\
	    	<div class="col-sm-8" style="background-color:none;">\
	    		<%= @comment.content %>\
	    	</div>\
  		</div>\
  		<span class="text-muted">\
		    Commented <%= time_ago_in_words(@comment.created_at) %> ago.\
		</span>\
	   	<% if current_user? @user %>\
	    	| <%= link_to "delete", @comment, method: :delete, remote: true, :class => "del-button"%>\
	  	<% end %>\
  		<hr>\
  	</div>');
 	var $comments_count = $('.comments-count');
	$comments_count.text(<%= @comments_count %>);
});

app/views/comments/destroy.js.erb
$(document).ready(function() {
	$(".del-button").bind('ajax:success', function() {  
 		$(this).closest(".comment").remove();
		$('.comments-count').text('<%= @comments_count - 1 %>');
	});
}); 

app/views/layouts/_footer.html.erb
<div class="container">
    <div class="row">
        <hr>
        <div class="col-xs-8">
            <ul class="list-unstyled list-inline pull-left">
                <li>
                    <%= link_to 'Sign in', signin_path %>
                </li>
                <li>
                    <%= link_to 'Sign up', sign_up_path %>
                </li>
                
                <li>
                    <%= link_to 'Help', help_path %> 
                </li>
                <li>
                    <%= link_to 'About', about_path %>
                </li>
            </ul>
        </div>
        <div class="col-xs-4">
            <p class="text-muted pull-right">© 2016 Blog by Anton. All rights reserved</p>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
                <span class="sr-only">Открыть анимацию</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <%= link_to "Blog", root_path, :class=>"navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="responsive-menu">
            <ul class="nav navbar-nav">
                <li><%= link_to "Home",    root_path %></li>
                <li><%= link_to "Help",    help_path %></li>
                <% if signed_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "My posts", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li><%= link_to "Create new post", new_post_path %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Sign out", signout_path, method: "delete" %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Sign in", signin_path %></li>
                    <li><%= link_to "Sign up!", sign_up_path %></li>
                <% end %>
            </ul>
            <% if !signed_in? %>
                <%= form_for(:session, url: sessions_path, html: { class: "navbar-form navbar-right hidden-sm"}) do |f| %>

                    
                    <%= f.text_field :name, class: 'form-control', :placeholder => "Name" %>

                    <%= f.password_field :password, class: 'form-control', :placeholder => "Password" %>

                    <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
                <% end %>
            <% else %>
                <%= link_to "Create new post", new_post_path, :class=>"btn btn-primary active pull-right", :style=>"margin-top: 10px;" %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog | <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
    
 	  <%= render 'layouts/footer' %>
    
</body>
</html>

app/views/posts/_all_posts.html.erb
<div class="row masonry well" data-columns>
	<% @posts.each do |post| %>
		<div class="item">
		    <div class="thumbnail">
		        <%= image_tag post.picture.url(:medium), :class=>"img-responsive" %>
		        <div class="caption">
		            <%= render post %>
		            <%= link_to "Подробнее", post, :class=>"btn btn-primary" %>
		        </div>
		    </div>
		</div>
	<% end %>
</div>
<%= javascript_include_tag "salvattore" %>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {role: "form"}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: "30", rows: "10" %>
  </div>

  <div class="form-group">
      <span class="btn btn-default btn-file">
        Browse file for picture
        <%= f.file_field :picture %>
      </span>
  </div>
  
  <%= f.submit "Create new post", :class => "btn btn-primary"%>
<% end %>

app/views/posts/_post.html.erb
<li>
	<h4>
		<span class="content">
			<%= link_to post.title, post_path(post.id) %>
		</span>
	</h4>
	<span class="content">
		<%= abbreviated_post(post) %>
	</span>
	<br>
	<span class="text-muted">
		Posted <%= time_ago_in_words(post.created_at) %> ago.
	</span>
	<br>
</li>

app/views/posts/new.html.erb
<%= provide(:title, 'Create post') %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="panel panel-default">
	  <div class="panel-heading">
      <h3><%= @post.title %></h3>
    </div>
	  <div class="panel-body">
      <%= image_tag @post.picture.url, :class=>"img-thumbnail img-responsive center-block" %>
      <%= @post.body %>
      <br><br>
      <span class="text-muted">
        Posted <%= time_ago_in_words(@post.created_at) %> ago.
      </span>
    </div>
</div>
<br>
<div class="comments">
	  <hr>
	  <h4> Comments(<span class="comments-count"><%= @comments.count %></span>) </h4>
	  <br>
    <div class="comments-render">
	    <%= render @comments %>
    </div>
	  <%= render 'comments/form' %>
	  <%= will_paginate @comments %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
About page

app/views/static_pages/contact.html.erb
Contact page

app/views/static_pages/help.html.erb
<div class="container well">
	
</div>

app/views/static_pages/index.html.erb
<%= render 'posts/all_posts' %>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true, role: "form"}  do |f| %>
	  <%= render 'shared/error_messages' %>
      <div class="form-group">
	      <%= f.label :name %>
	      <%= f.text_field :name, :class => "form-control" %>
	  </div>

	  <div class="form-group">
	      <%= f.label :password %>
	      <%= f.password_field :password, :class => "form-control"%>
      </div>

      <div class="form-group">
	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>
      <div class="form-group">
	      <span class="btn btn-default btn-file">
	      	Browse file for avatar
	      	<%= f.file_field :avatar %>
	      </span>
	  </div>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<br><hr>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<%= thumb_avatar_for user %>
			<h3><%= link_to user.name, user %></h3>
            <h6>Email: email@mail.ru</h6>
            <h6>Old: 20 Year</h6>
            <h6><%= link_to "All posts...", user %></h6>
		</div>

        <div class="col-md-8 col-lg-8">
        	<h3> <%= user.name %> posts</h3>
        	<% @posts = user.posts %>
     		<ul>
	        	<% @posts.each do |post| %>
	        		<li><%= link_to post.title, post_path(post.id) %></li>
	        	<% end %>
	        <ul>
        </div>
	</div>
</div>

app/views/users/create.html.erb
Created user
@user.name

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-3">
    <%= form_for(@user, html: {role: "form"}) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class=>"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class=>"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class=>"form-control" %>
      </div>
      
      <div class="form-group">
        <span class="btn btn-default btn-file">
          Browse file for avatar
          <%= f.file_field :avatar %>
        </span>
      </div>
      
      <%= f.submit 'Save changes', class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

	<div class="container">
	  	<%= render @users %>
	</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-3">
  	<h1>Sign up</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <% if @user.posts.any? %>
    <h3><%= @user.name %> posts (<%= @user.posts.count %>)</h3>
      <%= render 'posts/all_posts' %>
  <% end %>
</div>